const fs = require('fs');
const f = 'C:\\dev\\abu-kamil-pos\\src\\renderer\\scripts\\closing.js';
const lines = [];

// confirmSaveClosing
lines.push('function confirmSaveClosing() {');
lines.push('    const stats = closingData.stats || {};');
lines.push('    const expectedCash = parseFloat(stats.cash_total) || 0;');
lines.push('    const difference = actualCashAmount - expectedCash;');
lines.push('    const transfers = closingData.transfers || [];');
lines.push('    const overdueTransfers = closingData.overdueTransfers || [];');
lines.push('    const unresolvedOverdue = overdueTransfers.filter(t => !t._resolved);');
lines.push('');
lines.push('    const summaryEl = document.getElementById("confirmSummary");');
lines.push('    if (summaryEl) {');
lines.push('        let warnings = "";');
lines.push('');
lines.push('        if (unresolvedOverdue.length > 0) {');
lines.push('            warnings += "<div style=\\"background:#ff4444;color:#fff;padding:10px;border-radius:8px;margin:5px 0\\">"');
lines.push('                + "\\u26D4 يوجد " + unresolvedOverdue.length + " تحويل متأخر لم يُتخذ قرار بشأنه! يُنصح بالعودة لقسم التحويلات المتأخرة أعلاه."');
lines.push('                + "</div>";');
lines.push('        }');
lines.push('');
lines.push('        if (transfers.length > 0) {');
lines.push('            warnings += "<div class=\\"confirm-warning\\">\\u26A0 يوجد " + transfers.length + " تحويل معلق لم تتم مطابقته</div>";');
lines.push('        }');
lines.push('');
lines.push('        if (Math.abs(difference) > 0.5 && actualCashAmount > 0) {');
lines.push('            const diffType = difference > 0 ? "زيادة" : "نقص";');
lines.push('            warnings += "<div class=\\"confirm-warning\\">\\u26A0 يوجد " + diffType + " في الصندوق: " + formatCurrency(Math.abs(difference)) + "</div>";');
lines.push('        }');
lines.push('');
lines.push('        if (actualCashAmount === 0 && expectedCash > 0) {');
lines.push('            warnings += "<div class=\\"confirm-warning\\">\\u26A0 لم يتم إدخال المبلغ الفعلي في الصندوق</div>";');
lines.push('        }');
lines.push('');
lines.push('        summaryEl.innerHTML = "<div class=\\"confirm-details\\">"');
lines.push('            + "<div class=\\"confirm-row\\"><span>إجمالي المبيعات:</span><strong>" + formatCurrency(parseFloat(stats.sales_total)||0) + "</strong></div>"');
lines.push('            + "<div class=\\"confirm-row\\"><span>عدد الفواتير:</span><strong>" + (stats.sales_count||0) + "</strong></div>"');
lines.push('            + "<div class=\\"confirm-row\\"><span>النقد المتوقع:</span><strong>" + formatCurrency(expectedCash) + "</strong></div>"');
lines.push('            + "<div class=\\"confirm-row\\"><span>النقد الفعلي:</span><strong>" + formatCurrency(actualCashAmount) + "</strong></div>"');
lines.push('            + "<div class=\\"confirm-row\\"><span>الفرق:</span><strong>" + formatCurrency(difference) + "</strong></div>"');
lines.push('            + warnings + "</div>";');
lines.push('    }');
lines.push('    openModal("confirmModal");');
lines.push('}');
lines.push('');

// doSaveClosing
lines.push('async function doSaveClosing() {');
lines.push('    const btnConfirm = document.getElementById("btnConfirmSave");');
lines.push('    if (btnConfirm) { btnConfirm.disabled = true; btnConfirm.textContent = "جاري الحفظ..."; }');
lines.push('');
lines.push('    try {');
lines.push('        const stats = closingData.stats || {};');
lines.push('        const expectedCash = parseFloat(stats.cash_total) || 0;');
lines.push('        const difference = actualCashAmount - expectedCash;');
lines.push('        const overdueTransfers = closingData.overdueTransfers || [];');
lines.push('');
lines.push('        const closingRecord = {');
lines.push('            user_id: currentUser ? currentUser.id : 1,');
lines.push('            user_name: currentUser ? (currentUser.name || currentUser.username) : "admin",');
lines.push('            date: new Date().toISOString().split("T")[0],');
lines.push('            data: JSON.stringify({');
lines.push('                total_sales: parseFloat(stats.sales_total) || 0,');
lines.push('                invoice_count: parseInt(stats.sales_count) || 0,');
lines.push('                cash_total: parseFloat(stats.cash_total) || 0,');
lines.push('                transfers_total: parseFloat(stats.transfers_total) || 0,');
lines.push('                debts_total: parseFloat(stats.debts_total) || 0,');
lines.push('                pending_transfers_count: (closingData.transfers || []).length,');
lines.push('                pending_transfers_total: (closingData.transfers || []).reduce((s, t) => s + (parseFloat(t.amount)||0), 0),');
lines.push('                overdue_transfers_count: overdueTransfers.length,');
lines.push('                overdue_converted_to_debt: overdueTransfers.filter(t => t._convertedToDebt).length,');
lines.push('                overdue_deferred: overdueTransfers.filter(t => t._deferred).length,');
lines.push('                new_debts_count: (closingData.debts || []).filter(d => { const today = new Date().toISOString().split("T")[0]; return d.created_at && d.created_at.startsWith(today); }).length,');
lines.push('                actual_cash: actualCashAmount,');
lines.push('                expected_cash: expectedCash,');
lines.push('                cash_difference: difference,');
lines.push('                notes: closingNotes');
lines.push('            }),');
lines.push('            total_sales: parseFloat(stats.sales_total) || 0,');
lines.push('            total_cash: parseFloat(stats.cash_total) || 0,');
lines.push('            total_transfer: parseFloat(stats.transfers_total) || 0,');
lines.push('            total_debt: parseFloat(stats.debts_total) || 0,');
lines.push('            actual_cash: actualCashAmount,');
lines.push('            expected_cash: expectedCash,');
lines.push('            cash_difference: difference');
lines.push('        };');
lines.push('');
lines.push('        const result = await window.api.saveDailyClosing(closingRecord);');
lines.push('        if (result.success) {');
lines.push('            showToast("تم حفظ الإقفال بنجاح", "success");');
lines.push('            closeModal("confirmModal");');
lines.push('        } else {');
lines.push('            showToast("خطأ: " + (result.error || "فشل الحفظ"), "error");');
lines.push('        }');
lines.push('    } catch (e) {');
lines.push('        console.error("خطأ حفظ الإقفال:", e);');
lines.push('        showToast("خطأ في حفظ الإقفال", "error");');
lines.push('    } finally {');
lines.push('        if (btnConfirm) { btnConfirm.disabled = false; btnConfirm.textContent = "تأكيد الحفظ"; }');
lines.push('    }');
lines.push('}');
lines.push('');

fs.appendFileSync(f, '\n' + lines.join('\n'), 'utf8');
console.log('Part 4 done:', lines.length, 'new lines');
console.log('Total:', fs.readFileSync(f,'utf8').split('\n').length, 'lines');
