const fs = require('fs');
const f = 'C:\\dev\\abu-kamil-pos\\src\\renderer\\scripts\\closing.js';
const lines = [];

// printReport
lines.push('function printReport() {');
lines.push('    const stats = closingData.stats || {};');
lines.push('    const expectedCash = parseFloat(stats.cash_total) || 0;');
lines.push('    const difference = actualCashAmount - expectedCash;');
lines.push('    const today = new Date().toISOString().split("T")[0];');
lines.push('    const invoices = (closingData.invoices || []).filter(inv => inv.created_at && inv.created_at.startsWith(today));');
lines.push('    const todayDebts = (closingData.debts || []).filter(d => d.created_at && d.created_at.startsWith(today));');
lines.push('');
lines.push('    let html = "<html dir=\\"rtl\\"><head><meta charset=\\"utf-8\\"><title>تقرير الإقفال اليومي</title>";');
lines.push('    html += "<style>body{font-family:Arial,sans-serif;padding:20px;direction:rtl} table{width:100%;border-collapse:collapse;margin:10px 0} th,td{border:1px solid #ddd;padding:8px;text-align:right} th{background:#f5f5f5} h2{color:#333;border-bottom:2px solid #1976d2;padding-bottom:5px} .summary{display:flex;gap:15px;flex-wrap:wrap;margin:10px 0} .summary-item{background:#f0f4ff;padding:10px 15px;border-radius:8px;flex:1;min-width:120px;text-align:center} .summary-item .label{font-size:12px;color:#666} .summary-item .value{font-size:18px;font-weight:bold;color:#1976d2} @media print{body{padding:0}}</style>";');
lines.push('    html += "</head><body>";');
lines.push('    html += "<h1 style=\\"text-align:center\\">تقرير الإقفال اليومي</h1>";');
lines.push('    html += "<p style=\\"text-align:center\\">التاريخ: " + today + " | المستخدم: " + (currentUser ? currentUser.name || currentUser.username : "admin") + "</p>";');
lines.push('');
lines.push('    html += "<h2>ملخص المبيعات</h2>";');
lines.push('    html += "<div class=\\"summary\\">";');
lines.push('    html += "<div class=\\"summary-item\\"><div class=\\"label\\">الفواتير</div><div class=\\"value\\">" + (stats.sales_count||0) + "</div></div>";');
lines.push('    html += "<div class=\\"summary-item\\"><div class=\\"label\\">الإجمالي</div><div class=\\"value\\">" + formatCurrency(parseFloat(stats.sales_total)||0) + "</div></div>";');
lines.push('    html += "<div class=\\"summary-item\\"><div class=\\"label\\">النقد</div><div class=\\"value\\">" + formatCurrency(parseFloat(stats.cash_total)||0) + "</div></div>";');
lines.push('    html += "<div class=\\"summary-item\\"><div class=\\"label\\">التحويلات</div><div class=\\"value\\">" + formatCurrency(parseFloat(stats.transfers_total)||0) + "</div></div>";');
lines.push('    html += "<div class=\\"summary-item\\"><div class=\\"label\\">الديون</div><div class=\\"value\\">" + formatCurrency(parseFloat(stats.debts_total)||0) + "</div></div>";');
lines.push('    html += "</div>";');
lines.push('');
lines.push('    html += "<h2>مقارنة الصندوق</h2>";');
lines.push('    html += "<table><tr><th>المتوقع</th><th>الفعلي</th><th>الفرق</th></tr>";');
lines.push('    html += "<tr><td>" + formatCurrency(expectedCash) + "</td><td>" + formatCurrency(actualCashAmount) + "</td><td>" + formatCurrency(difference) + "</td></tr></table>";');
lines.push('');
lines.push('    if (invoices.length > 0) {');
lines.push('        html += "<h2>فواتير اليوم (" + invoices.length + ")</h2>";');
lines.push('        html += "<table><tr><th>#</th><th>الزبون</th><th>المبلغ</th><th>الوقت</th></tr>";');
lines.push('        invoices.forEach((inv, i) => {');
lines.push('            const time = inv.created_at ? inv.created_at.split(" ")[1] || "" : "";');
lines.push('            html += "<tr><td>" + (i+1) + "</td><td>" + (inv.customer_name||"زبون عام") + "</td><td>" + formatCurrency(parseFloat(inv.total)||0) + "</td><td>" + time + "</td></tr>";');
lines.push('        });');
lines.push('        html += "</table>";');
lines.push('    }');
lines.push('');
lines.push('    if (todayDebts.length > 0) {');
lines.push('        html += "<h2>ديون اليوم (" + todayDebts.length + ")</h2>";');
lines.push('        html += "<table><tr><th>الزبون</th><th>المبلغ</th><th>السبب</th></tr>";');
lines.push('        todayDebts.forEach(d => {');
lines.push('            html += "<tr><td>" + (d.customer_name||"") + "</td><td>" + formatCurrency(parseFloat(d.amount)||0) + "</td><td>" + (d.debt_reason||"") + "</td></tr>";');
lines.push('        });');
lines.push('        html += "</table>";');
lines.push('    }');
lines.push('');
lines.push('    if (closingNotes) { html += "<h2>ملاحظات</h2><p>" + closingNotes + "</p>"; }');
lines.push('    html += "</body></html>";');
lines.push('');
lines.push('    const printWin = window.open("", "_blank", "width=800,height=600");');
lines.push('    printWin.document.write(html);');
lines.push('    printWin.document.close();');
lines.push('    printWin.onload = () => { printWin.print(); };');
lines.push('}');
lines.push('');

// exportCSV
lines.push('function exportCSV() {');
lines.push('    const today = new Date().toISOString().split("T")[0];');
lines.push('    const invoices = (closingData.invoices || []).filter(inv => inv.created_at && inv.created_at.startsWith(today));');
lines.push('    let csv = "\\uFEFF#,الزبون,المبلغ,الوقت\\n";');
lines.push('    invoices.forEach((inv, i) => {');
lines.push('        const time = inv.created_at ? inv.created_at.split(" ")[1] || "" : "";');
lines.push('        csv += (i+1) + "," + (inv.customer_name||"زبون عام") + "," + (parseFloat(inv.total)||0) + "," + time + "\\n";');
lines.push('    });');
lines.push('    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });');
lines.push('    const link = document.createElement("a");');
lines.push('    link.href = URL.createObjectURL(blob);');
lines.push('    link.download = "closing_" + today + ".csv";');
lines.push('    link.click();');
lines.push('    showToast("تم تصدير التقرير", "success");');
lines.push('}');
lines.push('');

// convertToDebt
lines.push('async function convertToDebt(paymentId) {');
lines.push('    if (!confirm("هل تريد تحويل هذه الدفعة إلى دين على الزبون؟")) return;');
lines.push('    try {');
lines.push('        const result = await window.api.convertTransferToDebt(paymentId);');
lines.push('        if (result.success) {');
lines.push('            showToast("تم تحويل الدفعة إلى دين بنجاح", "success");');
lines.push('            const overdue = closingData.overdueTransfers || [];');
lines.push('            const item = overdue.find(t => t.id === paymentId);');
lines.push('            if (item) { item._resolved = true; item._convertedToDebt = true; }');
lines.push('            const card = document.getElementById("overdue-" + paymentId);');
lines.push('            if (card) {');
lines.push('                card.style.opacity = "0.5";');
lines.push('                card.innerHTML = "<div style=\\"text-align:center;padding:10px;color:#4CAF50\\">\\u2705 تم تحويلها إلى دين</div>";');
lines.push('            }');
lines.push('        } else {');
lines.push('            showToast("خطأ: " + (result.error || "فشل التحويل"), "error");');
lines.push('        }');
lines.push('    } catch (e) {');
lines.push('        console.error("خطأ تحويل لدين:", e);');
lines.push('        showToast("خطأ في العملية", "error");');
lines.push('    }');
lines.push('}');
lines.push('');

// deferTransfer
lines.push('function deferTransfer(paymentId) {');
lines.push('    const overdue = closingData.overdueTransfers || [];');
lines.push('    const item = overdue.find(t => t.id === paymentId);');
lines.push('    if (item) { item._resolved = true; item._deferred = true; }');
lines.push('    showToast("تم تأجيل التحويل ليوم غد", "info");');
lines.push('    const card = document.getElementById("overdue-" + paymentId);');
lines.push('    if (card) {');
lines.push('        card.style.opacity = "0.5";');
lines.push('        card.innerHTML = "<div style=\\"text-align:center;padding:10px;color:#FF9800\\">\\u23F3 مؤجّل ليوم غد</div>";');
lines.push('    }');
lines.push('}');
lines.push('');

// Helper functions
lines.push('function formatCurrency(amount) {');
lines.push('    return (parseFloat(amount) || 0).toFixed(2) + " \\u20AA";');
lines.push('}');
lines.push('');
lines.push('function formatDate(dateStr) {');
lines.push('    if (!dateStr) return "";');
lines.push('    try { return new Date(dateStr).toLocaleDateString("ar"); } catch(e) { return dateStr; }');
lines.push('}');
lines.push('');
lines.push('function getTransferTypeName(type) {');
lines.push('    const names = { "bank_transfer": "تحويل بنكي", "wallet": "محفظة", "now": "فوري", "later": "لاحق", "deferred": "مؤجل" };');
lines.push('    return names[type] || type || "تحويل";');
lines.push('}');
lines.push('');
lines.push('function openModal(id) {');
lines.push('    const modal = document.getElementById(id);');
lines.push('    if (modal) modal.classList.add("active");');
lines.push('}');
lines.push('');
lines.push('function closeModal(id) {');
lines.push('    const modal = document.getElementById(id);');
lines.push('    if (modal) modal.classList.remove("active");');
lines.push('}');
lines.push('');
lines.push('function showToast(message, type) {');
lines.push('    let container = document.getElementById("toastContainer");');
lines.push('    if (!container) { container = document.createElement("div"); container.id = "toastContainer"; container.className = "toast-container"; document.body.appendChild(container); }');
lines.push('    const toast = document.createElement("div");');
lines.push('    toast.className = "toast toast-" + (type || "info");');
lines.push('    toast.textContent = message;');
lines.push('    container.appendChild(toast);');
lines.push('    setTimeout(() => { toast.remove(); }, 3000);');
lines.push('}');
lines.push('');
lines.push('function handleLogout() {');
lines.push('    if (confirm("هل تريد تسجيل الخروج؟")) {');
lines.push('        sessionStorage.clear();');
lines.push('        localStorage.removeItem("currentUser");');
lines.push('        if (window.api && window.api.appRelaunch) { window.api.appRelaunch(); }');
lines.push('        else { window.location.href = "login.html"; }');
lines.push('    }');
lines.push('}');

fs.appendFileSync(f, '\n' + lines.join('\n'), 'utf8');
console.log('Part 5 done:', lines.length, 'new lines');
console.log('Total:', fs.readFileSync(f,'utf8').split('\n').length, 'lines');
